server:
  port: 8006


spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: consulPayment8006  #设置服务名称
        prefer-ip-address: true  #显示服务的IP地址

