server:
  port: 80

spring:
  application:
    name: cloud-provider-hystrix-order

# Eureka-Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: orderHystrix80    #设置服务名称
    prefer-ip-address: true   #显示服务的IP地址

#设置feign客户端超时时间（feign 支持 ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用的时间
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true
